# Generated by Django 2.2.4 on 2020-08-17 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
