# Generated by Django 2.2.4 on 2020-08-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200824_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='images', width_field='width'),
        ),
    ]
