# Generated by Django 2.2.4 on 2020-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200914_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chained_posts',
            field=models.ManyToManyField(related_name='_post_chained_posts_+', to='posts.Post'),
        ),
    ]
