# Generated by Django 2.2.4 on 2020-09-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_chained_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='chained_posts',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
