# Generated by Django 2.2.4 on 2020-09-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200915_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='chained_posts',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Post'),
        ),
    ]
