# Generated by Django 2.2.4 on 2020-10-29 00:27

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0005_auto_20201028_1827'),
        ('posts', '0018_auto_20200915_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tier',
        ),
        migrations.AddField(
            model_name='post',
            name='tier',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='coach', chained_model_field='coach', null=True, related_name='posts', to='tiers.Tier'),
        ),
    ]
