# Generated by Django 2.2.4 on 2020-10-29 00:27

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20201029_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tier',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='coach', chained_model_field='coach', horizontal=True, null=True, related_name='posts', to='tiers.Tier'),
        ),
    ]
