# Generated by Django 2.2.4 on 2020-10-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20201029_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tier',
            new_name='tiers',
        ),
    ]
