# Generated by Django 3.0.9 on 2021-01-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_post_linked_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PR', 'Processing'), ('DO', 'Done')], default='PR', max_length=2),
        ),
    ]
