# Generated by Django 3.1 on 2021-03-23 08:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0015_benefit_editable'),
        ('posts', '0031_auto_20210224_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tier',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='coach', chained_model_field='coach', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tiers.tier'),
        ),
    ]
