# Generated by Django 3.1 on 2021-06-16 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20210616_0109'),
        ('posts', '0032_auto_20210323_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='projects.project'),
        ),
    ]
