# Generated by Django 2.2.4 on 2020-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
