# Generated by Django 2.2.4 on 2020-10-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201014_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField()),
                ('completed_teams', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.Team')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgressLevel',
        ),
    ]
