# Generated by Django 2.2.4 on 2020-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20201014_2006'),
        ('projects', '0008_auto_20201021_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='subscribers.Subscriber'),
        ),
    ]
