# Generated by Django 2.2.4 on 2020-10-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='instructor.Coach'),
        ),
    ]
