# Generated by Django 2.2.4 on 2020-10-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20201030_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='completed_teams',
        ),
        migrations.AddField(
            model_name='milestone',
            name='completed_teams',
            field=models.ManyToManyField(blank=True, related_name='milestones', to='projects.Team'),
        ),
    ]
