# Generated by Django 2.2.4 on 2020-10-30 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20201030_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prerequisite',
            old_name='prerequisite',
            new_name='description',
        ),
    ]
