# Generated by Django 2.2.4 on 2020-10-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20201030_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='completed_teams',
            field=models.ManyToManyField(blank=True, related_name='milestones_completed', to='projects.Team'),
        ),
    ]
