# Generated by Django 2.2.4 on 2020-11-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20201123_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecompletionreport',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
