# Generated by Django 2.2.4 on 2020-11-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_milestonecompletionreport_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecompletionreport',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='projects.Milestone'),
        ),
    ]
