# Generated by Django 2.2.4 on 2020-11-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_milestonecompletionreport_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonecompletionreport',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.Milestone'),
        ),
    ]
