# Generated by Django 2.2.4 on 2020-11-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20201123_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonecompletionreport',
            name='members',
            field=models.ManyToManyField(related_name='milestone_reports', to='subscribers.Subscriber'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='subscribers.Subscriber'),
        ),
    ]
