# Generated by Django 2.2.4 on 2020-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20201123_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecompletionreport',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='PD', max_length=2),
        ),
    ]
