# Generated by Django 3.0.9 on 2020-12-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_milestonecompletionreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneCompletionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='images', width_field='width')),
                ('milestone_completion_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.MilestoneCompletionReport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
