# Generated by Django 3.0.9 on 2020-12-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_milestonecompletionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonecompletionimage',
            name='milestone_completion_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.MilestoneCompletionReport'),
        ),
    ]
