# Generated by Django 3.0.9 on 2020-12-09 00:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20201205_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
