# Generated by Django 3.1 on 2021-02-24 00:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_surrogate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneCompletionVideoAssetMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passthrough', models.UUIDField(default=uuid.uuid1)),
                ('milestone_completion_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.milestonecompletionreport')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneCompletionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passthrough', models.UUIDField(default=uuid.uuid1)),
                ('asset_id', models.CharField(max_length=120)),
                ('milestone_completion_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.milestonecompletionreport')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneCompletionPlaybackId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=30)),
                ('playback_id', models.CharField(max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_ids', to='projects.milestonecompletionvideo')),
            ],
        ),
    ]
