# Generated by Django 3.1 on 2021-02-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_milestonecompletionplaybackid_milestonecompletionvideo_milestonecompletionvideoassetmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecompletionreport',
            name='video_status',
            field=models.CharField(choices=[('PR', 'Processing'), ('DO', 'Done')], default='PR', max_length=2),
        ),
    ]
