# Generated by Django 3.1 on 2021-03-06 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_milestonecompletionplaybackid_milestonecompletionvideo_milestonecompletionvideoassetmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='milestonecompletionreport',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
