# Generated by Django 3.1 on 2021-02-26 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_milestonecompletionreport_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecompletionreport',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
