# Generated by Django 3.1 on 2021-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20210306_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecompletionreport',
            name='video_status',
            field=models.CharField(choices=[('PR', 'Processing'), ('DO', 'Done')], default='PR', max_length=2),
        ),
    ]
