# Generated by Django 3.1 on 2021-05-01 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_milestonecompletionreport_coach_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
