# Generated by Django 3.1 on 2021-05-12 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0023_auto_20210211_2053'),
        ('subscribers', '0007_subscription_price_id'),
        ('projects', '0030_team_surrogate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('coupon_id', models.CharField(blank=True, max_length=30, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='instructor.coach')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='subscribers.subscriber')),
            ],
        ),
    ]
