# Generated by Django 2.2.4 on 2020-10-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertisefields', '0005_auto_20201024_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisefieldavatar',
            name='expertise_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='expertisefields.ExpertiseField'),
        ),
    ]
