# Generated by Django 3.1 on 2021-05-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertisefields', '0006_auto_20201024_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseFieldSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
