# Generated by Django 3.1 on 2021-05-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0025_coach_submitted_expertise'),
        ('expertisefields', '0007_expertisefieldsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisefieldsuggestion',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_expertise', to='instructor.coach'),
        ),
    ]
