# Generated by Django 3.0.9 on 2020-12-02 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20201202_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='surrogate',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
