# Generated by Django 3.0.9 on 2020-12-02 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_surrogate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
