# Generated by Django 3.0.9 on 2020-11-26 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='surrogate',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
