# Generated by Django 3.0.9 on 2020-11-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20201123_1825'),
        ('chat', '0003_auto_20201126_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.Subscriber'),
        ),
    ]
