# Generated by Django 3.0.9 on 2020-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201126_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('TM', 'Team'), ('TC', 'Team with coach'), ('GL', 'General')], default='TM', max_length=2),
        ),
    ]
