# Generated by Django 3.1 on 2021-03-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_milestonecompletionreport_video_status'),
        ('chat', '0006_auto_20201126_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='projects.team'),
        ),
    ]
