# Generated by Django 3.1 on 2021-04-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210322_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='type',
            new_name='team_type',
        ),
    ]
