# Generated by Django 2.2.4 on 2020-11-11 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200820_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surrogate',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
