# Generated by Django 2.2.4 on 2020-11-11 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_surrogate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
