# Generated by Django 2.2.4 on 2020-08-17 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expertisefields', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='expertise_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expertisefields.ExpertiseField'),
        ),
        migrations.AddField(
            model_name='coach',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
