# Generated by Django 2.2.4 on 2020-08-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_auto_20200817_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
