# Generated by Django 2.2.4 on 2020-08-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20200820_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='static/images', width_field='width')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.Coach')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
