# Generated by Django 2.2.4 on 2020-09-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0009_auto_20200824_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='subscribers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
