# Generated by Django 2.2.4 on 2020-09-27 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0011_auto_20200920_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='coach',
            name='subscribers',
            field=models.ManyToManyField(null=True, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
