# Generated by Django 2.2.4 on 2020-10-14 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_auto_20201014_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
