# Generated by Django 2.2.4 on 2020-11-24 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_coach_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='surrogate',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
