# Generated by Django 3.0.9 on 2021-02-03 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20201123_1825'),
        ('instructor', '0017_auto_20201124_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='subscribers.Subscriber')),
            ],
        ),
    ]
