# Generated by Django 3.0.9 on 2021-02-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0018_coachapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachapplication',
            name='message',
            field=models.TextField(),
        ),
    ]
