# Generated by Django 3.0.9 on 2021-02-04 00:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0019_auto_20210203_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachapplication',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
