# Generated by Django 3.0.9 on 2021-02-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0020_coachapplication_surrogate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
