# Generated by Django 3.1 on 2021-02-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0022_coachapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='stripe_account_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='stripe_created',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='stripe_expires_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
