# Generated by Django 3.1 on 2021-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0023_auto_20210211_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='seen_welcome_page',
            field=models.BooleanField(default=False),
        ),
    ]
