# Generated by Django 3.1 on 2021-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0024_coach_seen_welcome_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='submitted_expertise',
            field=models.BooleanField(default=False),
        ),
    ]
