# Generated by Django 3.1 on 2021-07-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0025_coach_submitted_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coachapplication',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
