# Generated by Django 3.1 on 2021-08-14 20:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('instructor', '0026_auto_20210712_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
