# Generated by Django 3.1 on 2022-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0027_auto_20220121_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
