# Generated by Django 3.1 on 2022-01-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0027_auto_20220121_1550'),
        ('qa', '0002_qasession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_by',
        ),
        migrations.AddField(
            model_name='question',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_questions', to='instructor.coach'),
        ),
        migrations.AddField(
            model_name='question',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='initial_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
