# Generated by Django 3.1 on 2022-01-29 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0027_auto_20220121_1550'),
        ('qa', '0005_availabletimerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('body', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_questions', to='instructor.coach')),
            ],
        ),
    ]
