# Generated by Django 3.1 on 2022-02-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_commonquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninvitation',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('DC', 'Declined')], default='PD', max_length=2),
        ),
    ]
