# Generated by Django 3.1 on 2022-02-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_questioninvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasession',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='qa.question'),
        ),
        migrations.AddField(
            model_name='qasession',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qasession',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
