# Generated by Django 3.1 on 2022-02-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20220210_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qasession',
            name='question',
        ),
        migrations.RemoveField(
            model_name='qasession',
            name='zoom_link',
        ),
        migrations.RemoveField(
            model_name='qasession',
            name='zoom_password',
        ),
    ]
