# Generated by Django 2.2.4 on 2020-11-19 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
