# Generated by Django 2.2.4 on 2020-08-19 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0002_auto_20200817_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiers', models.CharField(choices=[('FR', 'Free'), ('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3')], default='FR', max_length=2)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='instructor.Coach')),
            ],
        ),
    ]
