# Generated by Django 2.2.4 on 2020-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='tiers',
            new_name='tier',
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('tier', 'coach'), name='unique_tier'),
        ),
    ]
