# Generated by Django 2.2.4 on 2020-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_auto_20200820_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
