# Generated by Django 2.2.4 on 2020-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0004_auto_20201028_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='subheading',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
