# Generated by Django 2.2.4 on 2020-11-20 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0005_auto_20201028_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
