# Generated by Django 3.0.9 on 2021-01-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0007_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
