# Generated by Django 3.0.9 on 2021-01-24 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0008_tier_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='surrogate',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
