# Generated by Django 3.0.9 on 2021-01-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0009_tier_surrogate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
