# Generated by Django 3.1 on 2021-02-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_subscription'),
        ('tiers', '0010_tier_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscriptions', to='subscribers.Subscription'),
        ),
    ]
