# Generated by Django 3.1 on 2021-02-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0012_auto_20210208_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='subscriptions',
        ),
    ]
