# Generated by Django 3.1 on 2021-03-10 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0013_remove_tier_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='deprecated_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
