# Generated by Django 3.1 on 2021-03-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0014_auto_20210310_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
