# Generated by Django 3.1 on 2021-02-07 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20201123_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='subscribers.subscriber')),
            ],
        ),
    ]
