# Generated by Django 3.1 on 2021-02-09 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0013_remove_tier_subscriptions'),
        ('subscribers', '0004_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='customer_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tiers.tier'),
        ),
    ]
