# Generated by Django 3.1 on 2021-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_auto_20210310_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
