# Generated by Django 3.1 on 2021-09-12 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20210616_0118'),
        ('subscribers', '0007_subscription_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_seen_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_seen_by', to='posts.post'),
        ),
    ]
