# Generated by Django 3.1 on 2021-04-20 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20210312_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardbase',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
