# Generated by Django 3.1 on 2021-04-20 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_milestonecompletionreport_coach_feedback'),
        ('awards', '0003_awardbase_surrogate'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='projects.milestone'),
        ),
        migrations.AlterField(
            model_name='award',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='awardbase',
            name='surrogate',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
